### PR TITLE
add colored output

### PR DESCRIPTION
**Pull request by yonip23**
Hi!
I used [this crate](https://github.com/mackwic/colored) to add colours to the output:
image
image

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
Hey!

The screenshots look super nice, I'd love to land such a feature!

**Comment by yonip23** [comment]
> Hey!
> 
> The screenshots look super nice, I'd love to land such a feature!

Happy to hear!
Why are the tests fail? I only changed so little haha

**Comment by o0Ignition0o** [comment]
I think codecov is sad because the changes aren't covered by unit tests, which is yet an other reason why i should disable this :p

**Review by o0Ignition0o — APPROVED** [review]
This looks great!

As a followup, we might be able to add internal macros such as `success! warning! error! and info!` that would take something and make it cyan / green / red etc... so it's more explicit the colors have a meaning!

**Comment by o0Ignition0o** [comment]
@yonip23 i m ready to merge this when you think we're good to go! 🎉

**Comment by yonip23** [comment]
> This looks great!
> 
> As a followup, we might be able to add internal macros such as `success! warning! error! and info!` that would take something and make it cyan / green / red etc... so it's more explicit the colors have a meaning!

This is a great idea, would you like it to be on this PR or should this be in another one?

**Comment by yonip23** [comment]
> @yonip23 i m ready to merge this when you think we're good to go! tada

If you want the macros in another pr then go ahead an merge this one :)

**Comment by o0Ignition0o** [comment]
> This is a great idea, would you like it to be on this PR or should this be in another one?

let's do it in a followup, so you can officially be part of the cargo-scout contributors! 🎉

**Pull request merged**
