### PR TITLE
adding macros for less verbose output colouring

### PR DESCRIPTION
**Pull request by yonip23**
Everything looks the same
image

(I added this line just to see how an error print looks like):
image

### CODE REVIEW

**Comment by yonip23** [comment]
@o0Ignition0o Please take a careful look at my changes to see that the colours are correct in every print. thanks!

**Comment by o0Ignition0o** [comment]
wow this is great! it even allows us to remove the odd empty brackets from println!("{}", "stuff".cyan()) \o/

lgtm, ready to merge when you think we're good to go!

**Review by o0Ignition0o — APPROVED** [review]

**Comment by yonip23** [comment]
> wow this is great! it even allows us to remove the odd empty brackets from println!("{}", "stuff".cyan()) \o/
> 
> lgtm, ready to merge when you think we're good to go!

thanks so much for the kind and quick replies! you can merge this :)

**Comment by o0Ignition0o** [comment]
> thanks so much for the kind and quick replies! you can merge this :)

Well thank you for the pull requests, it s super nice!

**Pull request merged**
